### ISSUE TITLE
Apache site config will not serve static assets for apps deployed to root of the host.

### ISSUE THREAD

**Issue by grosscol** [mlibrary/ansible-predeploy#21]
Apache rewrite rules to accommodate serving from root or a relative_root.  The existing apache site template when given `/` as the `app_url_root` will yield:

```
  # Serve static assets through apache
  RewriteCond /hydra-dev/vanilla-sufia-staging/shared/public/$1 -f
  RewriteRule ^/(.*)$  /hydra-dev/vanilla-sufia-staging/shared/public$1 [L]
​
  # Reverse proxy application to app hostname and port
  RewriteRule ^(/.*)$ http://app-vanilla-sufia-staging:30066$1 [P]
  ProxyPassReverse / http://app-vanilla-sufia-staging:30066/
```

For applications being served out of root, RewriteRule needs to have a trailing `/`.  So use:
`RewriteRule ^/(.*)$  /hydra-dev/vanilla-sufia-staging/shared/public/$1 [L]`
Notice the slash: `public`**/**`$1`

The existing RewriteRule is needed for applications being served out of a relative_root.
### Summary

Use RewriteRule with explicit trailing slash for applications served out of hosts root url.
User RewriteRule without explicit trailing slash for applications served from a relative root url.

**Comment by aelkiss** [comment]
Fixed by #37, #44
