### ISSUE TITLE
Multiple db hosts is broken

### ISSUE THREAD

**Issue by malakai97** [mlibrary/ansible-predeploy#27]
Manually specifying the private db host in db_host_priv_ip works if and only if there is exactly one db host.

**Comment by aelkiss** [comment]
For this and #28 is the use case deploying to multiple sites? It seems like if you are manually specifying the private IP you need to track the mapping between app & db host, which seems annoying; workaround for now (until we have a solution for #4) might just be separate configs for each site?

**Comment by malakai97** [comment]
We may want to consider a private fork of this project. @grosscol

**Comment by grosscol** [comment]
Do we have instances where an application has multiple db hosts at the same site?  I think the ansible inventory handles this kind of thing for us.  The geo-specific examples in the inventory documentation for ansible seem to address this directly.

eg. Huston DB Host and Atlanta DB Host

**Comment by aelkiss** [comment]
We do not currently have instances where there are multiple production database hosts at a single site.
