### ISSUE TITLE
App server may not be able to create and chown a directory if it is nfs mounted

### ISSUE THREAD

**Issue by malakai97** [mlibrary/ansible-predeploy#35]
The workaround is to skip creation if the dir already exists and is configured correctly.  

Long term, the predeploy could create this directory on the nfs host.

**Comment by malakai97** [comment]
I have an implementation of the workaround.

**Comment by grosscol** [comment]
I've seen this with capistrano as well.   The create directory doesn't return quickly enough with nfs.  I have to pause between creating a directory and modifying it in any way.

**Comment by malakai97** [comment]
That's a separate issue.  This was just a permissions problem.
