### ISSUE TITLE
In the web group, map private app host ip

### ISSUE THREAD

**Issue by malakai97** [mlibrary/ansible-predeploy#5]
Webservers need to know the private IP of the app servers.  This should be supplied in `/etc/hosts` and should use an alias of the form `app-{{app_name}}`

For example, `umrdr` and `umrdr-staging` would be come `app-umrdr` and `app-umrdr-staging`, respectively.

**Comment by grosscol** [comment]
Changed the setup role to provide the correctly prefixed name for the hostname with commit b6a4e7e.

``` ruby
    apache_app_hostname:      "app-{{app_name}}"
```

The apache_config role writes the supplied private ip and apache_app_hostname to /etc/hosts
