### ISSUE TITLE
In the app group, map private db host ip 

### ISSUE THREAD

**Issue by malakai97** [mlibrary/ansible-predeploy#6]
App servers need to know the private IPs of the db servers.  This should be supplied in `/etc/hosts` and should use an alias of the form `db-{{app_name}}`

For example, `umrdr` and `umrdr-staging` would be come `db-umrdr` and `db-umrdr-staging`, respectively.

**Comment by grosscol** [comment]
What role should this be a part of?  puma-svc? db-user?  or should this go into a new role?

**Comment by grosscol** [comment]
Adding db host to /etc/hosts in the target role.

**Comment by grosscol** [comment]
Closed by commit b86679.
